// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
)

const createFeed = `-- name: CreateFeed :exec
INSERT INTO feeds(title, url) VALUES (?, ?)
`

type CreateFeedParams struct {
	Title string
	URL   string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) error {
	_, err := q.db.ExecContext(ctx, createFeed, arg.Title, arg.URL)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id, title, url, created_at, updated_at, last_refreshed_at, image FROM feeds WHERE id = ?
`

func (q *Queries) GetFeed(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.URL,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRefreshedAt,
		&i.Image,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, title, url, created_at, updated_at, last_refreshed_at, image FROM feeds ORDER BY created_at DESC
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRefreshedAt,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedImage = `-- name: UpdateFeedImage :exec
UPDATE feeds SET image = ? WHERE id = ?
`

type UpdateFeedImageParams struct {
	Image *string
	ID    int64
}

func (q *Queries) UpdateFeedImage(ctx context.Context, arg UpdateFeedImageParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedImage, arg.Image, arg.ID)
	return err
}

const updateFeedLastRefreshedAt = `-- name: UpdateFeedLastRefreshedAt :exec
UPDATE feeds SET last_refreshed_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateFeedLastRefreshedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateFeedLastRefreshedAt, id)
	return err
}
