// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
)

const createFeed = `-- name: CreateFeed :exec
INSERT INTO feeds(title, url) VALUES (?, ?)
`

type CreateFeedParams struct {
	Title string
	URL   string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) error {
	_, err := q.db.ExecContext(ctx, createFeed, arg.Title, arg.URL)
	return err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, title, url, created_at, updated_at, last_refreshed_at FROM feeds ORDER BY created_at DESC
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedLastRefreshedAt = `-- name: UpdateFeedLastRefreshedAt :exec
UPDATE feeds SET last_refreshed_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateFeedLastRefreshedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateFeedLastRefreshedAt, id)
	return err
}
