// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"time"
)

const countItems = `-- name: CountItems :one
SELECT COUNT(*) FROM items WHERE items.status = ?
`

func (q *Queries) CountItems(ctx context.Context, status Status) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItems, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO items(feed_id, title, link, description, published_at) VALUES (?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	FeedID      int64
	Title       string
	Link        string
	Description string
	PublishedAt time.Time
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Description,
		arg.PublishedAt,
	)
	return err
}

const listItems = `-- name: ListItems :many
SELECT items.id, items.feed_id, items.title, items.link, items.description, items.status, items.published_at, items.created_at, items.updated_at, feeds.id, feeds.title, feeds.url, feeds.created_at, feeds.updated_at, feeds.last_refreshed_at FROM items
JOIN feeds ON items.feed_id = feeds.id
WHERE items.status = ?
ORDER BY items.published_at DESC
LIMIT ? OFFSET ?
`

type ListItemsParams struct {
	Status Status
	Limit  int64
	Offset int64
}

type ListItemsRow struct {
	ID          int64
	FeedID      int64
	Title       string
	Link        string
	Description string
	Status      Status
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   *time.Time
	Feed        Feed
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItems, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Description,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Feed.ID,
			&i.Feed.Title,
			&i.Feed.URL,
			&i.Feed.CreatedAt,
			&i.Feed.UpdatedAt,
			&i.Feed.LastRefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllItemsAsRead = `-- name: MarkAllItemsAsRead :exec
UPDATE items SET status = "read" WHERE status = "unread"
`

func (q *Queries) MarkAllItemsAsRead(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllItemsAsRead)
	return err
}

const updateItemStatus = `-- name: UpdateItemStatus :exec
UPDATE items SET status = ? WHERE id = ?
`

type UpdateItemStatusParams struct {
	Status Status
	ID     int64
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateItemStatus, arg.Status, arg.ID)
	return err
}
