// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"time"
)

const checkItemExists = `-- name: CheckItemExists :one
SELECT id, feed_id, title, link, description, status, published_at, created_at, updated_at, hash FROM items WHERE feed_id = ? AND hash = ?
`

type CheckItemExistsParams struct {
	FeedID int64
	Hash   string
}

func (q *Queries) CheckItemExists(ctx context.Context, arg CheckItemExistsParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, checkItemExists, arg.FeedID, arg.Hash)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.Description,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hash,
	)
	return i, err
}

const countItems = `-- name: CountItems :one
SELECT COUNT(*) FROM items
WHERE (CAST (?1 AS BOOL)  = 0 OR items.status  = ?2)
AND   (CAST (?3 AS BOOL) = 0 OR items.feed_id = ?4)
`

type CountItemsParams struct {
	HasStatus bool
	Status    Status
	HasFeedID bool
	FeedID    int64
}

func (q *Queries) CountItems(ctx context.Context, arg CountItemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItems,
		arg.HasStatus,
		arg.Status,
		arg.HasFeedID,
		arg.FeedID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO items(feed_id, title, link, description, hash, published_at) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	FeedID      int64
	Title       string
	Link        string
	Description string
	Hash        string
	PublishedAt time.Time
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Description,
		arg.Hash,
		arg.PublishedAt,
	)
	return err
}

const listItems = `-- name: ListItems :many
SELECT items.id, items.feed_id, items.title, items.link, items.description, items.status, items.published_at, items.created_at, items.updated_at, items.hash, feeds.id, feeds.title, feeds.url, feeds.created_at, feeds.updated_at, feeds.last_refreshed_at, feeds.image FROM items
JOIN feeds ON items.feed_id = feeds.id
WHERE (CAST (? AS BOOL)  = 0 OR items.status  = ?)
AND   (CAST (? AS BOOL) = 0 OR items.feed_id = ?)
ORDER BY items.published_at DESC
LIMIT ? OFFSET ?
`

type ListItemsParams struct {
	HasStatus bool
	Status    Status
	HasFeedID bool
	FeedID    int64
	Limit     int64
	Offset    int64
}

type ListItemsRow struct {
	Item Item
	Feed Feed
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItems,
		arg.HasStatus,
		arg.Status,
		arg.HasFeedID,
		arg.FeedID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.Item.ID,
			&i.Item.FeedID,
			&i.Item.Title,
			&i.Item.Link,
			&i.Item.Description,
			&i.Item.Status,
			&i.Item.PublishedAt,
			&i.Item.CreatedAt,
			&i.Item.UpdatedAt,
			&i.Item.Hash,
			&i.Feed.ID,
			&i.Feed.Title,
			&i.Feed.URL,
			&i.Feed.CreatedAt,
			&i.Feed.UpdatedAt,
			&i.Feed.LastRefreshedAt,
			&i.Feed.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllItemsAsRead = `-- name: MarkAllItemsAsRead :exec
UPDATE items SET status = "read" WHERE status = "unread"
`

func (q *Queries) MarkAllItemsAsRead(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllItemsAsRead)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items SET title = ?, link = ?, description = ?, published_at = ? WHERE id = ?
`

type UpdateItemParams struct {
	Title       string
	Link        string
	Description string
	PublishedAt time.Time
	ID          int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.Title,
		arg.Link,
		arg.Description,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}

const updateItemStatus = `-- name: UpdateItemStatus :one
UPDATE items SET status = ? WHERE id = ? RETURNING id, feed_id, title, link, description, status, published_at, created_at, updated_at, hash
`

type UpdateItemStatusParams struct {
	Status Status
	ID     int64
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItemStatus, arg.Status, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.Description,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hash,
	)
	return i, err
}
