// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Feed struct {
	ID              int64
	Title           string
	URL             string
	CreatedAt       time.Time
	UpdatedAt       *time.Time
	LastRefreshedAt *time.Time
	Image           *string
}

type Item struct {
	ID          int64
	FeedID      int64
	Title       string
	Link        string
	Description string
	Status      Status
	Hash        string
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}
