// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID        int64
	Title     string
	URL       string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
