// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID              int64
	Title           string
	URL             string
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	LastRefreshedAt sql.NullTime
	Image           sql.NullString
}

type Item struct {
	ID          int64
	FeedID      int64
	Title       string
	Link        string
	Description string
	Status      Status
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	Hash        string
}
